# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a10fa84e080b56308f06ae25a5a35015"
name = "luxury-vertical-app"
handle = "luxury-vertical-app-14"
application_url = "https://tablet-render-ccd-peaceful.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tablet-render-ccd-peaceful.trycloudflare.com/auth/callback",
  "https://tablet-render-ccd-peaceful.trycloudflare.com/auth/shopify/callback",
  "https://tablet-render-ccd-peaceful.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "faey2023.myshopify.com"
automatically_update_urls_on_dev = true
